// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoOFtyz8Eq7lqQPB4AY8dj2LaPxZHQyMk',
    appId: '1:110307106423:web:b16865535bad53bd0e7072',
    messagingSenderId: '110307106423',
    projectId: 'mu-transit',
    authDomain: 'mu-transit.firebaseapp.com',
    storageBucket: 'mu-transit.firebasestorage.app',
    measurementId: 'G-YCENFFYNYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASF5xsdsPM7v_xXNZyjK4EpMKpL0VbBd4',
    appId: '1:110307106423:android:4d28567e881d478b0e7072',
    messagingSenderId: '110307106423',
    projectId: 'mu-transit',
    storageBucket: 'mu-transit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTw2jRO68hgaQnLUPx3RZ6dop8BBNJOlo',
    appId: '1:110307106423:ios:3d93cfe866d653fe0e7072',
    messagingSenderId: '110307106423',
    projectId: 'mu-transit',
    storageBucket: 'mu-transit.firebasestorage.app',
    iosBundleId: 'com.example.muTransit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTw2jRO68hgaQnLUPx3RZ6dop8BBNJOlo',
    appId: '1:110307106423:ios:3d93cfe866d653fe0e7072',
    messagingSenderId: '110307106423',
    projectId: 'mu-transit',
    storageBucket: 'mu-transit.firebasestorage.app',
    iosBundleId: 'com.example.muTransit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoOFtyz8Eq7lqQPB4AY8dj2LaPxZHQyMk',
    appId: '1:110307106423:web:1dfbdd3e3c6016c40e7072',
    messagingSenderId: '110307106423',
    projectId: 'mu-transit',
    authDomain: 'mu-transit.firebaseapp.com',
    storageBucket: 'mu-transit.firebasestorage.app',
    measurementId: 'G-MBGZ0SQHG3',
  );
}
