// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB9TdCF8aVdE_cdrNQEYLHe0RSQhR2ogA',
    appId: '1:749747574328:web:a69c8ca7542c6a261438cd',
    messagingSenderId: '749747574328',
    projectId: 'mu-transit-51918',
    authDomain: 'mu-transit-51918.firebaseapp.com',
    storageBucket: 'mu-transit-51918.firebasestorage.app',
    measurementId: 'G-S45TVFBDC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsXoFUFnVmqKktBOp16WWDeEiOEaw6r2U',
    appId: '1:749747574328:android:3b3ee90a6172194d1438cd',
    messagingSenderId: '749747574328',
    projectId: 'mu-transit-51918',
    storageBucket: 'mu-transit-51918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi6u4LbsbmlUil9NY1I8cwk32Mi5lwX3k',
    appId: '1:749747574328:ios:86bfc6bcc0a67d4f1438cd',
    messagingSenderId: '749747574328',
    projectId: 'mu-transit-51918',
    storageBucket: 'mu-transit-51918.firebasestorage.app',
    iosBundleId: 'com.example.muTransit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi6u4LbsbmlUil9NY1I8cwk32Mi5lwX3k',
    appId: '1:749747574328:ios:86bfc6bcc0a67d4f1438cd',
    messagingSenderId: '749747574328',
    projectId: 'mu-transit-51918',
    storageBucket: 'mu-transit-51918.firebasestorage.app',
    iosBundleId: 'com.example.muTransit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB9TdCF8aVdE_cdrNQEYLHe0RSQhR2ogA',
    appId: '1:749747574328:web:2df0ecc35a5a16f91438cd',
    messagingSenderId: '749747574328',
    projectId: 'mu-transit-51918',
    authDomain: 'mu-transit-51918.firebaseapp.com',
    storageBucket: 'mu-transit-51918.firebasestorage.app',
    measurementId: 'G-EMRRDV4Y8M',
  );
}
