// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp758t-JL0GdNmHFdAOhTcd0iUuPVSAd0',
    appId: '1:686407735144:web:1a444571eaa69965f0e8dd',
    messagingSenderId: '686407735144',
    projectId: 'mu-transit-86f0a',
    authDomain: 'mu-transit-86f0a.firebaseapp.com',
    databaseURL: 'https://mu-transit-86f0a-default-rtdb.firebaseio.com',
    storageBucket: 'mu-transit-86f0a.firebasestorage.app',
    measurementId: 'G-SPV6HX6EBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC73cWwOPFxJS9Nxfx8Dsr9hNBl0P0MMcw',
    appId: '1:686407735144:android:e7a46ff5e9c25827f0e8dd',
    messagingSenderId: '686407735144',
    projectId: 'mu-transit-86f0a',
    databaseURL: 'https://mu-transit-86f0a-default-rtdb.firebaseio.com',
    storageBucket: 'mu-transit-86f0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn2WQOi0VsUecLf5gO38VeoFIQq6INAx4',
    appId: '1:686407735144:ios:9b63bb3a0179b34cf0e8dd',
    messagingSenderId: '686407735144',
    projectId: 'mu-transit-86f0a',
    databaseURL: 'https://mu-transit-86f0a-default-rtdb.firebaseio.com',
    storageBucket: 'mu-transit-86f0a.firebasestorage.app',
    iosBundleId: 'com.example.locationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn2WQOi0VsUecLf5gO38VeoFIQq6INAx4',
    appId: '1:686407735144:ios:9b63bb3a0179b34cf0e8dd',
    messagingSenderId: '686407735144',
    projectId: 'mu-transit-86f0a',
    databaseURL: 'https://mu-transit-86f0a-default-rtdb.firebaseio.com',
    storageBucket: 'mu-transit-86f0a.firebasestorage.app',
    iosBundleId: 'com.example.locationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp758t-JL0GdNmHFdAOhTcd0iUuPVSAd0',
    appId: '1:686407735144:web:0514290ddb71b53af0e8dd',
    messagingSenderId: '686407735144',
    projectId: 'mu-transit-86f0a',
    authDomain: 'mu-transit-86f0a.firebaseapp.com',
    databaseURL: 'https://mu-transit-86f0a-default-rtdb.firebaseio.com',
    storageBucket: 'mu-transit-86f0a.firebasestorage.app',
    measurementId: 'G-XEPNVGQ2PY',
  );
}
